name: Hello World

on:
  pull_request:
    branches: [main]
  workflow_run:
    workflows: ["Version Increase after Dependency Update"]
    types: [completed]

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello World"
