# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: '0522013'
_src_path: https://github.com/SchulzSystemtechnik/iiot-workflow-templates.git
check_version: false
code_check: false
docker_hub_name: schulzsystemtechnik/...
docker_release: false
github_release: false
linter_type: null
poetry_version: 1.2.2
project_type: python_poetry
python_version: '3.10'
python_versions:
- '3.8'
- '3.9'
- '3.10'
- '3.11'
renovate_increase_version: true

