[tool.poetry]
name = "my-test"
version = "0.1.2"
description = ""
authors = ["Philipp Jaschke <philipp.jaschke@schulz.st>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "0.102.0"
pydantic = "2.4.1"
trio = "^0.21.0"
tccli-intl-en = "^3.0.811.0"
cdk-lambda-subminute = "^2.0.275"
cdk-aurora-globaldatabase = "2.3.319"
test234 = {git = "https://github.com/PJ-Schulz/test234.git", tag = "2.7.3"}
redis = {git = "https://github.com/redis/redis-py.git", tag = "v5.0.0"}

[tool.poetry.group.dev.dependencies]
pytest = "7.4.2"
hypothesis = "6.88.1"
flake8 = "6.0.0"
isort = "5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
