[tool.poetry]
name = "my-test"
version = "0.2.1"
description = ""
authors = ["Philipp Jaschke <philipp.jaschke@schulz.st>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "0.102.0"
pydantic = "2.4.2"
trio = "0.23.1"
cdk-lambda-subminute = "2.0.294"
cdk-aurora-globaldatabase = "2.3.326"
test234 = {git = "https://github.com/PJ-Schulz/test234.git", tag = "2.7.5"}
redis = {git = "https://github.com/redis/redis-py.git", tag = "v5.0.1"}

[tool.poetry.group.dev.dependencies]
pytest = "7.4.3"
hypothesis = "6.88.3"
flake8 = "6.1.0"
isort = "5.12.0"
pepperize-cdk-ses-smtp-credentials = "0.3.552"
pepperize-cdk-organizations = "0.7.733"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
