[tool.poetry]
name = "my-test"
version = "0.1.0"
description = ""
authors = ["Philipp Jaschke <philipp.jaschke@schulz.st>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "0.102.0"
pydantic = "2.4.2"
trio = "^0.22.0"
tccli-intl-en = "^3.0.811.1"
cdk-lambda-subminute = "^2.0.277"
cdk-aurora-globaldatabase = "2.3.314"
test234 = {git = "https://github.com/PJ-Schulz/test234.git", tag = "2.7.4"}
redis = {git = "https://github.com/redis/redis-py.git", tag = "v4.6.0"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
hypothesis = "^6.88.1"
flake8 = "^6.1.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
