name: Github Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  github_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.9"
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.3.0

      - name: Set env
        run: echo "POETRY_NEW=$(poetry version --short)" >> $GITHUB_ENV

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.POETRY_NEW }}
          name: "v.${{ env.POETRY_NEW }}"
          commit: main
          generateReleaseNotes: true
          token: ${{ github.token }}