name: Github Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  get_tags:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      poetryTag: ${{ steps.poetryTag.outputs.poetryTag }}
      latestTag: ${{ steps.latestTag.outputs.latestTag }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2.3.4
        with:
          python-version: "3.9"
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.3.0

      - name: Get Poetry Tag
        id: poetryTag
        run: echo "poetryTag=$(poetry version --short)" >> $GITHUB_ENV

      - name: 'Get Latest Tag'
        id: latestTag
        uses: JinoArch/get-latest-tag@latest

  make_release:
    needs: ["get_tags"]
    if: jobs.get_tags.outputs.poetryTag != jobs.get_tags.outputs.latestTag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.poetryTag.outputs.POETRY_TAG }}
          name: "v.${{ steps.poetryTag.outputs.POETRY_TAG }}"
          commit: main
          generateReleaseNotes: true
          token: ${{ github.token }}