name: Github Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  github_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2.3.4
        with:
          python-version: "3.9"
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.3.0

      - name: Get Poetry Tag
        id: poetryTag
        run: echo "POETRY_TAG=$(poetry version --short)" >> $GITHUB_ENV
      - name: 'Get Latest Tag'
        id: latestTag
        uses: JinoArch/get-latest-tag@latest

      - uses: ncipollo/release-action@v1
        if: steps.poetryTag.outputs.POETRY_TAG != steps.latestTag.outputs.latestTag
        with:
          tag: ${{ steps.poetryTag.outputs.POETRY_TAG }}
          name: "v.${{ steps.poetryTag.outputs.POETRY_TAG }}"
          commit: main
          generateReleaseNotes: true
          token: ${{ github.token }}