name: Hello World

on:
  pull_request:
    branches: [main]

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello World"
