name: Test05

on:
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  test-job-05:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' &&
      (!contains(github.event.head_commit.message, 'fix(deps)') || !contains(github.event.head_commit.message, 'chore(deps)'))
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World 3"

      - run: echo "${{github.event_name}}"
      - run: echo "${{github.ref}}"
      - run: echo "${{github.actor}}"
      - run: echo "${{github.workflow}}"

      - run: echo "${{github.event.before}}"
      - run: echo "${{github.event.after}}"

      - run: echo "${{github.event.merged }}"
      - run: echo "${{github.event.status }}"
