name: Test03

on:
  pull_request:
    types: [closed]
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  test-job-03:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World 3"

      - run: echo "${{github.event_name}}"
      - run: echo "${{github.ref}}"
      - run: echo "${{github.actor}}"
      - run: echo "${{github.workflow}}"

      - run: echo "${{github.event.before}}"
      - run: echo "${{github.event.after}}"

      - run: echo "${{github.event.merged }}"
      - run: echo "${{github.event.status }}"

      - run: echo "${{ toJson(github.event) }}"
