name: Unittest

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - "main"

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install poetry
        run: pip install poetry==1.2.2
        shell: bash

      - run: |
          git config --global credential.helper cache
          echo "https://${{ secrets.PAT }}@github.com" > $HOME/.git-credentials
          poetry install

      - name: Say Hello
        run: echo "Hello World"
