name: Unittest

on:
  pull_request:
    branches: [main]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install poetry
        run: pip install poetry==1.2.2
        shell: bash

      - name: Poetry install
        run: |
          echo "https://${{ secrets.PAT }}:@github.com" > $HOME/.git-credentials
          cat $HOME/.git-credentials
          git config --global credential.helper store
          poetry config virtualenvs.in-project true
          poetry install
          rm -f $HOME/.git-credentials

      - name: Say Hello
        run: echo "Hello World"
